-- Criar o banco de dados se não existir
CREATE DATABASE IF NOT EXISTS `hospital_uc12` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;

-- Usar o banco de dados
USE `hospital_uc12`;

-- Definir o fuso horário padrão
SET time_zone = '+00:00';

-- Desativar verificações de chaves únicas e estrangeiras temporariamente
SET FOREIGN_KEY_CHECKS = 0;
SET UNIQUE_CHECKS = 0;

-- Criar tabelas

-- Tabela: especialidade
CREATE TABLE IF NOT EXISTS `especialidade` (
  `ID_ESPECIALIDADE` INT NOT NULL PRIMARY KEY,
  `DESCRICAO_ESPEC` VARCHAR(45) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Tabela: convenio
CREATE TABLE IF NOT EXISTS `convenio` (
  `ID_CONVENIO` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `NOME_CONVENIO` VARCHAR(45) DEFAULT NULL,
  `TEMPO_CARENCIA` VARCHAR(45) DEFAULT NULL,
  `CNPJ` VARCHAR(45) DEFAULT NULL
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Tabela: medico
CREATE TABLE IF NOT EXISTS `medico` (
  `ID_MEDICO` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `CRM` VARCHAR(45) DEFAULT NULL,
  `ENDERECO` VARCHAR(45) DEFAULT NULL,
  `TELEFONE` VARCHAR(45) DEFAULT NULL,
  `EMAIL` VARCHAR(45) DEFAULT NULL,
  `DATA_NASC` DATE DEFAULT NULL,
  `UF` VARCHAR(45) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Tabela: paciente
CREATE TABLE IF NOT EXISTS `paciente` (
  `ID_PACIENTE` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `NOME` VARCHAR(45) DEFAULT NULL,
  `ENDERECO` VARCHAR(45) DEFAULT NULL,
  `DATA_NASC` DATE DEFAULT NULL,
  `TELEFONE` VARCHAR(45) DEFAULT NULL,
  `CPF` VARCHAR(45) DEFAULT NULL,
  `RG` VARCHAR(45) DEFAULT NULL,
  `ID_CONVENIO_FK` INT NOT NULL,
  CONSTRAINT `fk_PACIENTE_CONVENIO1` FOREIGN KEY (`ID_CONVENIO_FK`) REFERENCES `convenio` (`ID_CONVENIO`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Tabela: medico_especialidade
CREATE TABLE IF NOT EXISTS `medico_especialidade` (
  `ID_MEDICO` INT NOT NULL,
  `ID_ESPECIALIDADE` INT NOT NULL,
  PRIMARY KEY (`ID_MEDICO`,`ID_ESPECIALIDADE`),
  CONSTRAINT `FK_ID_ESPEC` FOREIGN KEY (`ID_ESPECIALIDADE`) REFERENCES `especialidade` (`ID_ESPECIALIDADE`),
  CONSTRAINT `FK_ID_MEDICO` FOREIGN KEY (`ID_MEDICO`) REFERENCES `medico` (`ID_MEDICO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Tabela: consulta
CREATE TABLE IF NOT EXISTS `consulta` (
  `ID_CONSULTA` INT NOT NULL PRIMARY KEY,
  `DATA_HORA` DATETIME DEFAULT NULL,
  `VALOR` DOUBLE DEFAULT NULL,
  `NUM_CARTEIRA_CONV` VARCHAR(45) DEFAULT NULL,
  `ID_CONVENIO_FK` INT NOT NULL,
  `ID_PACIENTE_FK` INT NOT NULL,
  `ID_MEDICO_FK` INT NOT NULL,
  `ID_ESPECIALIDADE_FK` INT NOT NULL,
  CONSTRAINT `fk_CONSULTA_CONVENIO1` FOREIGN KEY (`ID_CONVENIO_FK`) REFERENCES `convenio` (`ID_CONVENIO`),
  CONSTRAINT `fk_CONSULTA_ESPECIALIDADE1` FOREIGN KEY (`ID_ESPECIALIDADE_FK`) REFERENCES `especialidade` (`ID_ESPECIALIDADE`),
  CONSTRAINT `fk_CONSULTA_MEDICO1` FOREIGN KEY (`ID_MEDICO_FK`) REFERENCES `medico` (`ID_MEDICO`),
  CONSTRAINT `fk_CONSULTA_PACIENTE1` FOREIGN KEY (`ID_PACIENTE_FK`) REFERENCES `paciente` (`ID_PACIENTE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Tabela: receita_medica
CREATE TABLE IF NOT EXISTS `receita_medica` (
  `ID_RECEITA_MEDICA` INT NOT NULL PRIMARY KEY,
  `MEDICAMENTOS` VARCHAR(45) DEFAULT NULL,
  `QUANTIDADE` VARCHAR(45) DEFAULT NULL,
  `INSTRUCAO_USO` VARCHAR(45) DEFAULT NULL,
  `ID_CONSULTA_FK` INT NOT NULL,
  CONSTRAINT `fk_RECEITA_MEDICA_CONSULTA1` FOREIGN KEY (`ID_CONSULTA_FK`) REFERENCES `consulta` (`ID_CONSULTA`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Ativar verificações de chaves únicas e estrangeiras
SET FOREIGN_KEY_CHECKS = 1;
SET UNIQUE_CHECKS = 1;
